PREFIX bibo:   <http://purl.org/ontology/bibo/>
PREFIX dce:    <http://purl.org/dc/elements/1.1/>
PREFIX prov:   <http://www.w3.org/ns/prov#>

SELECT ?authors
FROM <http://ns.inria.fr/d2kab/graph/wheatgenomicsslkg>
WHERE {
    <{id}>
        dct:creator ?authors.
}
