PREFIX dct: <http://purl.org/dc/terms/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


SELECT *
FROM <http://ns.inria.fr/d2kab/graph/wheatgenomicsslkg>
WHERE {

    OPTIONAL { <{id}> dct:title ?title.
     FILTER isLiteral(?title)}
    OPTIONAL { <{id}> dct:issued ?date.}    
    OPTIONAL { <{id}> dct:source ?pub.}
    OPTIONAL { <{id}> dct:language ?lang.}
    OPTIONAL { <{id}> dct:abstract ?abstract.
    ?subject <http://purl.org/vocab/frbr/core#partOf> ?abstract .
    ?subject rdf:value ?abs.}

}
