PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX oa:     <http://www.w3.org/ns/oa#>
PREFIX schema: <http://schema.org/>
prefix frbr:    <http://purl.org/vocab/frbr/core#>
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?document ?title ?date (group_concat(distinct ?author, "$") as ?authors) (group_concat(distinct ?matchedEntity, "$$") as ?matchedEntities)
FROM <http://ns.inria.fr/d2kab/graph/wheatgenomicsslkg>
from <http://purl.obolibrary.org/obo/ncbitaxon/ncbitaxon.owl>
WHERE {
   ?document a schema:ScholarlyArticle.

      ?a1 oa:hasTarget [ oa:hasSource ?source ];
          oa:hasBody ?entityUri.
      ?source frbr:partOf+ ?document.

      ?entityUri rdfs:subClassOf* <{id}>;
                 rdfs:label ?entityLabel.

        BIND(concat(?entityUri, '$', ?entityLabel) as ?matchedEntity)
    
    OPTIONAL { ?document dct:title ?title.FILTER isLiteral(?title)}
    OPTIONAL { ?document dct:creator ?author.}
    OPTIONAL { ?document dct:issued ?date.}

} group by ?document ?title ?date
limit 20000