PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX oa:     <http://www.w3.org/ns/oa#>
PREFIX schema: <http://schema.org/>
prefix frbr:    <http://purl.org/vocab/frbr/core#>
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos:    <http://www.w3.org/2004/02/skos/core#>


SELECT ?document ?title ?date (group_concat(distinct ?author, "$") as ?authors) (group_concat(distinct ?matchedEntity, "$$") as ?matchedEntities)
FROM <http://ns.inria.fr/d2kab/graph/wheatgenomicsslkg>
From <http://ns.inria.fr/d2kab/ontology/wto/v3>
WHERE {
   ?document a schema:ScholarlyArticle.
   
    ?a1 oa:hasTarget [ oa:hasSource ?source ];
        oa:hasBody ?entityUri.
    ?source frbr:partOf+ ?document.
    {
        ?entityUri rdfs:subClassOf* <{id}>;
                rdfs:label ?entityLabel.
    } union {
        ?entityUri rdf:type/rdfs:subClassOf* <{id}>;
                skos:prefLabel ?entityLabel.
    }

    BIND(concat(?entityUri, '$', ?entityLabel) as ?matchedEntity)
    
    OPTIONAL { ?document dct:title ?title. FILTER isLiteral(?title)}
    OPTIONAL { ?document dct:creator ?author.}
    OPTIONAL { ?document dct:issued ?date.}

} group by ?document ?title ?date
limit 20000