PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX oa:     <http://www.w3.org/ns/oa#>
prefix frbr:    <http://purl.org/vocab/frbr/core#>
PREFIX schema: <http://schema.org/>

SELECT ?document ?title ?date (group_concat(distinct ?author, "$") as ?authors)

FROM <http://ns.inria.fr/d2kab/graph/wheatgenomicsslkg>
WHERE {
?document a schema:ScholarlyArticle.

{triples}

OPTIONAL { ?document dct:title ?title.FILTER isLiteral(?title)}
OPTIONAL { ?document dct:creator ?author.}
OPTIONAL { ?document dct:issued ?date.}

} group by ?document ?title ?date 
limit 20000
